# Generated by Django 5.2.3 on 2025-08-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRMergeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this configuration profile', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this configuration')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default configuration profile')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('validate_fhir', models.BooleanField(default=True, help_text='Perform FHIR validation on resources')),
                ('resolve_conflicts', models.BooleanField(default=True, help_text='Enable automatic conflict resolution')),
                ('deduplicate_resources', models.BooleanField(default=True, help_text='Enable automatic resource deduplication')),
                ('create_provenance', models.BooleanField(default=True, help_text='Create provenance tracking for all operations')),
                ('default_conflict_strategy', models.CharField(choices=[('newest_wins', 'Newest Data Wins'), ('preserve_both', 'Preserve Both Values'), ('manual_review', 'Flag for Manual Review'), ('confidence_based', 'Use Confidence Scores')], default='newest_wins', help_text='Default conflict resolution strategy', max_length=20)),
                ('deduplication_tolerance_hours', models.IntegerField(default=24, help_text='Time window for considering resources as potential duplicates')),
                ('near_duplicate_threshold', models.FloatField(default=0.9, help_text='Similarity threshold for near-duplicate detection (0.0-1.0)')),
                ('fuzzy_duplicate_threshold', models.FloatField(default=0.7, help_text='Similarity threshold for fuzzy duplicate detection (0.0-1.0)')),
                ('max_processing_time_seconds', models.IntegerField(default=300, help_text='Maximum time allowed for merge processing (seconds)')),
                ('advanced_config', models.JSONField(blank=True, default=dict, help_text='Advanced configuration options in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_fhir_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHIR Merge Configuration',
                'verbose_name_plural': 'FHIR Merge Configurations',
                'db_table': 'fhir_merge_configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FHIRMergeConfigurationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='JSON representation of changes made')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='fhir.fhirmergeconfiguration')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHIR Merge Configuration Audit',
                'verbose_name_plural': 'FHIR Merge Configuration Audits',
                'db_table': 'fhir_merge_configuration_audit',
                'ordering': ['-timestamp'],
            },
        ),
    ]
