# Generated by Django 5.2.3 on 2025-08-09 06:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('fhir', '0001_initial'),
        ('patients', '0002_alter_patienthistory_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRMergeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this merge operation', primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('single_document', 'Single Document Merge'), ('batch_documents', 'Batch Document Merge'), ('reconciliation', 'Data Reconciliation'), ('manual_merge', 'Manual Merge Operation')], default='single_document', help_text='Type of merge operation being performed', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial_success', 'Partial Success')], default='pending', help_text='Current status of the merge operation', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('current_step', models.CharField(blank=True, help_text='Current processing step description', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the operation was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the operation started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the operation completed', null=True)),
                ('merge_result', models.JSONField(blank=True, default=dict, help_text='Complete merge result object with statistics')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Error details if operation failed')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Total processing time in seconds', null=True)),
                ('resources_processed', models.IntegerField(default=0, help_text='Number of FHIR resources processed')),
                ('conflicts_detected', models.IntegerField(default=0, help_text='Number of conflicts detected')),
                ('conflicts_resolved', models.IntegerField(default=0, help_text='Number of conflicts resolved')),
                ('webhook_sent', models.BooleanField(default=False, help_text='Whether webhook notification has been sent')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to send webhook notification to')),
                ('webhook_sent_at', models.DateTimeField(blank=True, help_text='When webhook was sent', null=True)),
                ('configuration', models.ForeignKey(help_text='Configuration profile used for this merge', on_delete=django.db.models.deletion.PROTECT, related_name='merge_operations', to='fhir.fhirmergeconfiguration')),
                ('created_by', models.ForeignKey(help_text='User who initiated this operation', on_delete=django.db.models.deletion.PROTECT, related_name='created_merge_operations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Document being merged (for single document operations)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fhir_merge_operations', to='documents.document')),
                ('patient', models.ForeignKey(help_text='Patient this merge operation is for', on_delete=django.db.models.deletion.PROTECT, related_name='fhir_merge_operations', to='patients.patient')),
            ],
            options={
                'db_table': 'fhir_merge_operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='fhir_merge__patient_e2ee44_idx'), models.Index(fields=['created_by', 'created_at'], name='fhir_merge__created_0ba184_idx'), models.Index(fields=['status', 'created_at'], name='fhir_merge__status_d2b970_idx'), models.Index(fields=['operation_type', 'status'], name='fhir_merge__operati_635ba0_idx')],
            },
        ),
    ]
