# Generated by Django 5.2.3 on 2025-08-27 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the role', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Role name (e.g., 'admin', 'provider', 'staff', 'auditor')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable role name for display in UI', max_length=150)),
                ('description', models.TextField(help_text='Detailed description of role responsibilities and access level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active and can be assigned')),
                ('is_system_role', models.BooleanField(default=False, help_text='Whether this is a system-defined role (cannot be deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this role was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this role was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this role', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions assigned to this role', related_name='roles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='roles_name_a96913_idx'), models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx'), models.Index(fields=['created_at'], name='roles_created_e4bab6_idx')],
            },
        ),
    ]
