# Generated by Django 5.2.3 on 2025-08-27 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_role_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list, help_text="List of allowed IP ranges in CIDR notation (e.g., ['192.168.1.0/24'])")),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last IP address used for login', null=True)),
                ('require_mfa', models.BooleanField(default=True, help_text='Whether this user requires multi-factor authentication')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this user account is temporarily locked')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='When the account lockout expires (if locked)', null=True)),
                ('department', models.CharField(blank=True, help_text="User's department or division", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="User's job title or position", max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='user_profiles', to='accounts.role')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['user__email'],
                'indexes': [models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'), models.Index(fields=['last_login_ip'], name='user_profil_last_lo_7dbb72_idx'), models.Index(fields=['is_locked'], name='user_profil_is_lock_a03fc6_idx'), models.Index(fields=['created_at'], name='user_profil_created_26443b_idx')],
            },
        ),
    ]
