# Generated by Django 5.2.3 on 2025-09-06 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the invitation', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invited provider', max_length=254)),
                ('token', models.CharField(help_text='Secure token for invitation link', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted (null if not accepted)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invitation is still active')),
                ('personal_message', models.TextField(blank=True, help_text='Optional personal message to include in the invitation')),
                ('invited_by', models.ForeignKey(help_text='Administrator who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role to be assigned to the provider upon registration', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'Provider Invitation',
                'verbose_name_plural': 'Provider Invitations',
                'db_table': 'provider_invitations',
                'ordering': ['-created_at'],
                'permissions': [('manage_invitations', 'Can manage provider invitations')],
                'indexes': [models.Index(fields=['email'], name='provider_in_email_6d3e38_idx'), models.Index(fields=['token'], name='provider_in_token_522a03_idx'), models.Index(fields=['is_active', 'expires_at'], name='provider_in_is_acti_691d74_idx'), models.Index(fields=['invited_by', 'created_at'], name='provider_in_invited_58aa15_idx'), models.Index(fields=['role'], name='provider_in_role_id_cc59ef_idx')],
            },
        ),
    ]
