# Generated by Django 5.2.3 on 2025-06-24 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('document_upload', 'Document Upload'), ('document_process', 'Document Processing'), ('patient_create', 'Patient Created'), ('patient_update', 'Patient Updated'), ('patient_view', 'Patient Viewed'), ('provider_create', 'Provider Created'), ('provider_update', 'Provider Updated'), ('provider_view', 'Provider Viewed'), ('report_generate', 'Report Generated'), ('profile_update', 'Profile Updated')], help_text='Type of activity performed', max_length=50)),
                ('description', models.CharField(help_text='Human-readable description of the activity', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where activity originated (for HIPAA compliance)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information (for HIPAA compliance)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text="Type of object this activity relates to (e.g., 'patient', 'document')", max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of the related object', max_length=50, null=True)),
                ('user', models.ForeignKey(help_text='User who performed the activity', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'core_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_9d1bf3_idx'), models.Index(fields=['activity_type', '-timestamp'], name='core_activi_activit_f25345_idx'), models.Index(fields=['-timestamp'], name='core_activi_timesta_268bcf_idx')],
            },
        ),
    ]
