# Generated by Django 5.2.3 on 2025-07-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('phi_access', 'PHI Data Access'), ('phi_create', 'PHI Data Creation'), ('phi_update', 'PHI Data Update'), ('phi_delete', 'PHI Data Deletion'), ('phi_export', 'PHI Data Export'), ('document_upload', 'Document Upload'), ('document_download', 'Document Download'), ('document_view', 'Document View'), ('document_delete', 'Document Delete'), ('patient_create', 'Patient Created'), ('patient_update', 'Patient Updated'), ('patient_view', 'Patient Viewed'), ('patient_search', 'Patient Search'), ('fhir_export', 'FHIR Export'), ('fhir_import', 'FHIR Import'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('admin_access', 'Admin Panel Access'), ('config_change', 'Configuration Change'), ('security_violation', 'Security Violation'), ('data_breach', 'Data Breach Incident'), ('unauthorized_access', 'Unauthorized Access Attempt')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('system_admin', 'System Administration'), ('security', 'Security'), ('compliance', 'Compliance')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_url', models.URLField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, max_length=50)),
                ('phi_involved', models.BooleanField(db_index=True, default=False)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('monthly', 'Monthly Summary'), ('quarterly', 'Quarterly Summary'), ('annual', 'Annual Summary'), ('incident', 'Incident Report'), ('audit', 'Audit Report')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_events', models.IntegerField(default=0)),
                ('phi_access_events', models.IntegerField(default=0)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('security_violations', models.IntegerField(default=0)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('recommendations', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='compliance_reports/')),
            ],
            options={
                'db_table': 'compliance_reports',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['report_type', 'timestamp'], name='compliance__report__3cdd1b_idx'), models.Index(fields=['period_start', 'period_end'], name='compliance__period__9a6cd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mitigation_steps', models.TextField(blank=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='core.auditlog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'event_type'], name='audit_logs_timesta_da0de5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['patient_mrn', 'timestamp'], name='audit_logs_patient_81a2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['phi_involved', 'timestamp'], name='audit_logs_phi_inv_1179cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_logs_severit_549d29_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['category', 'timestamp'], name='audit_logs_categor_0633bd_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['threat_level', 'status'], name='security_ev_threat__ea285a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['timestamp', 'threat_level'], name='security_ev_timesta_6ee1db_idx'),
        ),
    ]
