# Generated by Django 5.2.3 on 2025-07-27 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_object_id_for_uuid_support'),
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_session', models.UUIDField(help_text='Unique identifier for processing session (handles multi-chunk docs)')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)')], db_index=True, help_text='AI service provider used', max_length=50)),
                ('model', models.CharField(db_index=True, help_text='Specific AI model used (e.g., claude-3-sonnet, gpt-3.5-turbo)', max_length=100)),
                ('input_tokens', models.PositiveIntegerField(help_text='Number of input tokens sent to API')),
                ('output_tokens', models.PositiveIntegerField(help_text='Number of output tokens received from API')),
                ('total_tokens', models.PositiveIntegerField(help_text='Total tokens used (input + output)')),
                ('cost_usd', models.DecimalField(decimal_places=6, help_text='Calculated cost in USD for this API call', max_digits=10)),
                ('processing_started', models.DateTimeField(help_text='When API call was initiated')),
                ('processing_completed', models.DateTimeField(help_text='When API call completed')),
                ('processing_duration_ms', models.PositiveIntegerField(help_text='Processing time in milliseconds')),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Whether the API call succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if API call failed', null=True)),
                ('chunk_number', models.PositiveIntegerField(blank=True, help_text='For chunked documents, which chunk this was (1-based)', null=True)),
                ('total_chunks', models.PositiveIntegerField(blank=True, help_text='Total number of chunks for this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('document', models.ForeignKey(help_text='Document being processed', on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='documents.document')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient associated with the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document'], name='api_usage_l_documen_6fb86b_idx'), models.Index(fields=['patient'], name='api_usage_l_patient_b1ec4a_idx'), models.Index(fields=['processing_session'], name='api_usage_l_process_6c59bd_idx'), models.Index(fields=['provider', 'model'], name='api_usage_l_provide_51c65b_idx'), models.Index(fields=['created_at'], name='api_usage_l_created_c81af4_idx'), models.Index(fields=['success', 'created_at'], name='api_usage_l_success_71d711_idx'), models.Index(fields=['cost_usd'], name='api_usage_l_cost_us_81e944_idx')],
            },
        ),
    ]
