# Generated by Django 5.2.3 on 2025-08-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apiusagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_audit_trail', 'Can view audit trail reports'), ('export_audit_logs', 'Can export audit logs to CSV'), ('manage_audit_system', 'Can manage audit logging system')]},
        ),
    ]
