# Generated by Django 5.2.3 on 2026-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusagelog',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('aws_textract', 'AWS Textract (OCR)')], db_index=True, help_text='AI service provider used', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('phi_access', 'PHI Data Access'), ('phi_create', 'PHI Data Creation'), ('phi_update', 'PHI Data Update'), ('phi_delete', 'PHI Data Deletion'), ('phi_export', 'PHI Data Export'), ('document_upload', 'Document Upload'), ('document_download', 'Document Download'), ('document_view', 'Document View'), ('document_delete', 'Document Delete'), ('document_requires_review', 'Document Requires Manual Review'), ('patient_create', 'Patient Created'), ('patient_update', 'Patient Updated'), ('patient_view', 'Patient Viewed'), ('patient_search', 'Patient Search'), ('fhir_export', 'FHIR Export'), ('fhir_import', 'FHIR Import'), ('ocr_sync_completed', 'Sync OCR Processing Completed'), ('ocr_async_job_started', 'Async OCR Job Started'), ('ocr_async_job_polling', 'Async OCR Job Status Check'), ('ocr_async_job_completed', 'Async OCR Job Completed'), ('ocr_async_job_timeout', 'Async OCR Job Timed Out'), ('ocr_async_job_failed', 'Async OCR Job Failed'), ('ocr_temp_upload', 'OCR Temp File Uploaded to S3'), ('ocr_temp_delete', 'OCR Temp File Deleted from S3'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('admin_access', 'Admin Panel Access'), ('config_change', 'Configuration Change'), ('security_violation', 'Security Violation'), ('data_breach', 'Data Breach Incident'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('data_validation', 'Document Pipeline Data Validation'), ('cache_cleared', 'Application Cache Cleared'), ('slow_request', 'Slow Request Detected'), ('rbac_access', 'Role-Based Access Log'), ('web_access_audit', 'Sensitive Path Web Access')], db_index=True, max_length=50),
        ),
    ]
