# Generated by Django 5.2.3 on 2025-08-27 18:46

import apps.documents.models
import django.core.validators
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=apps.documents.models.EncryptedFileField(help_text='Uploaded document file (PDF only) - encrypted at rest for HIPAA compliance', upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.documents.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Additional notes about this document - encrypted at rest')),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_text',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Extracted text from PDF - encrypted at rest')),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='review_notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Notes from manual review - encrypted at rest')),
        ),
    ]
