# Generated by Django 5.2.3 on 2025-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='capture_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='FHIR data capture metrics and analysis'),
        ),
    ]
