# Generated by Django 5.2.3 on 2025-09-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_capture_metrics_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='source_snippets',
            field=models.JSONField(blank=True, default=dict, help_text='Source text context (200-300 chars) around extracted values for snippet-based review'),
        ),
    ]
