# Generated by Django 5.2.3 on 2025-09-18 03:23

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_create_patient_data_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_log',
            field=models.JSONField(blank=True, default=list, help_text='Detailed error log with timestamps and context for debugging'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='AI processing time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='structured_data',
            field=django_cryptography.fields.encrypt(models.JSONField(blank=True, default=dict, help_text='Structured medical data extracted by AI using Pydantic models - encrypted at rest')),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='fallback_method_used',
            field=models.CharField(blank=True, help_text="Fallback extraction method used if primary AI failed (e.g., 'regex', 'gpt-fallback')", max_length=50),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='structured_extraction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata from structured Pydantic extraction including resource counts and validation info'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='corrections',
            field=models.JSONField(default=dict, help_text='Manual corrections to extracted data (also stores structured data if available)'),
        ),
    ]
