# Generated by Django 5.2.3 on 2025-09-24 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_structured_data_fields'),
        ('patients', '0005_convert_to_hybrid_encryption'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'processing_attempts'], name='doc_status_attempts_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_size', 'status'], name='doc_size_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['processed_at'], name='doc_processed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['patient', 'processed_at'], name='doc_patient_processed_idx'),
        ),
    ]
