# Generated by Django 5.2.3 on 2025-09-30 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_performance_indexes'),
        ('patients', '0005_convert_to_hybrid_encryption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='clinical_date',
            field=models.DateField(blank=True, help_text='Extracted or manually entered clinical date for this document/data', null=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='date_source',
            field=models.CharField(blank=True, choices=[('extracted', 'AI Extracted'), ('manual', 'Manually Entered')], help_text='Source of the clinical date (AI extracted or manually entered)', max_length=20),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='date_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified')], default='pending', help_text='Verification status of the clinical date', max_length=20),
        ),
        migrations.AddIndex(
            model_name='parseddata',
            index=models.Index(fields=['clinical_date', 'date_status'], name='parsed_data_clinica_619c42_idx'),
        ),
        migrations.AddIndex(
            model_name='parseddata',
            index=models.Index(fields=['patient', 'clinical_date'], name='parsed_data_patient_465177_idx'),
        ),
    ]
