# Generated by Django 5.2.3 on 2025-11-23 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_add_clinical_date_tracking'),
        ('patients', '0008_patient_living_setting_patient_primary_condition_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Ready to Merge'), ('rejected', 'Rejected - Do Not Use'), ('flagged', 'Flagged - Needs Attention')], db_index=True, default='pending', help_text='Current review status of the extraction', max_length=20),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Whether extracted data is approved for merging'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed (approved/rejected) this parsed data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parseddata',
            index=models.Index(fields=['document', 'review_status'], name='parsed_data_documen_2b75fd_idx'),
        ),
    ]
