# Generated by Django 5.2.3 on 2025-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_parseddata_rejection_reason_parseddata_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_message',
            field=models.CharField(blank=True, help_text='Current granular processing step description', max_length=255),
        ),
    ]
