# Generated by Django 5.2.3 on 2025-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_processing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='auto_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this extraction was automatically approved for immediate merge'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason why this extraction was flagged for manual review (if applicable)'),
        ),
    ]
