# Generated by Django 5.2.3 on 2025-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_add_optimistic_concurrency_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('auto_approved', 'Auto-Approved - Merged Immediately'), ('flagged', 'Flagged - Needs Manual Review'), ('reviewed', 'Reviewed - Manually Approved'), ('rejected', 'Rejected - Do Not Use')], db_index=True, default='pending', help_text='Current review status of the extraction (5-state machine for optimistic concurrency)', max_length=20),
        ),
    ]
