# Generated by Django 5.2.3 on 2025-12-02 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_update_review_status_choices_5state'),
        ('patients', '0008_patient_living_setting_patient_primary_condition_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parseddata',
            index=models.Index(fields=['review_status', 'created_at'], name='parsed_review_status_idx'),
        ),
    ]
