# Generated by Django 5.2.3 on 2026-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_migrate_review_status_to_5state_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('ocr_pending', 'OCR Pending'), ('completed', 'Completed'), ('failed', 'Processing Failed'), ('review', 'Needs Review'), ('requires_review', 'Requires Review')], db_index=True, default='pending', help_text='Current processing status', max_length=25),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use review_status field instead. Kept for backward compatibility only.'),
        ),
    ]
