# Generated by Django 5.2.3 on 2026-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_remove_document_review_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_extraction_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='AI structured extraction time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fhir_conversion_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='FHIR conversion time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_extraction_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='PDF/OCR text extraction time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='queue_wait_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Time spent waiting in queue before processing started (milliseconds)', null=True),
        ),
    ]
