# Generated by Django 5.2.3 on 2026-06-09 19:35

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_stage_timing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(help_text='Zero-based position of this chunk within the document')),
                ('content_hash', models.CharField(help_text='SHA-256 of chunk text + extraction version + model; invalidates stale checkpoints', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Extraction outcome for this chunk', max_length=10)),
                ('structured_json', django_cryptography.fields.encrypt(models.JSONField(blank=True, default=dict, help_text='StructuredMedicalExtraction dump for this chunk - encrypted at rest'))),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Input tokens billed for this chunk (excludes cache reads)')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Output tokens billed for this chunk')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated API cost for this chunk in USD', max_digits=10)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of extraction attempts for this chunk')),
                ('error_message', models.TextField(blank=True, help_text='Last error message if extraction failed (no PHI)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunk_results', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_chunk_results',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'status'], name='document_ch_documen_40df1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index', 'content_hash'), name='unique_document_chunk_hash')],
            },
        ),
    ]
