# Generated by Django 5.2.3 on 2025-07-07 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npi', models.CharField(help_text='National Provider Identifier', max_length=10, unique=True, verbose_name='NPI Number')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Provider Created'), ('updated', 'Provider Updated'), ('linked_to_document', 'Linked to Document'), ('unlinked_from_document', 'Unlinked from Document')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of what changed')),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_records', to='providers.provider')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider History',
                'verbose_name_plural': 'Provider Histories',
                'db_table': 'provider_history',
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['npi'], name='providers_npi_df1406_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['specialty'], name='providers_special_2869e4_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['organization'], name='providers_organiz_0f27b6_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['last_name', 'first_name'], name='providers_last_na_a63836_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['created_at'], name='providers_created_0fc16b_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhistory',
            index=models.Index(fields=['provider', 'changed_at'], name='provider_hi_provide_39b50f_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhistory',
            index=models.Index(fields=['action', 'changed_at'], name='provider_hi_action_86e367_idx'),
        ),
    ]
