# Generated by Django 5.2.3 on 2025-08-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Patient Created'), ('updated', 'Patient Updated'), ('fhir_append', 'FHIR Resources Added'), ('fhir_history_preserved', 'FHIR Historical Data Preserved'), ('document_processed', 'Document Processed')], max_length=50),
        ),
    ]
