# Generated by Django 5.2.3 on 2025-08-25 16:18

import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_encrypted_phi_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='encounter_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of encounter dates for quick searching'),
        ),
        migrations.AddField(
            model_name='patient',
            name='encrypted_fhir_bundle',
            field=django_cryptography.fields.encrypt(models.JSONField(blank=True, default=dict, help_text='Complete FHIR data with PHI (encrypted)')),
        ),
        migrations.AddField(
            model_name='patient',
            name='provider_references',
            field=models.JSONField(blank=True, default=list, help_text='List of provider references for quick searching'),
        ),
        migrations.AddField(
            model_name='patient',
            name='searchable_medical_codes',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted medical codes without PHI (unencrypted for fast searching)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=django_cryptography.fields.encrypt(models.CharField(help_text='YYYY-MM-DD format', max_length=10)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['searchable_medical_codes'], name='idx_medical_codes'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['encounter_dates'], name='idx_encounter_dates'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['provider_references'], name='idx_provider_refs'),
        ),
    ]
