# Generated by Django 5.2.3 on 2025-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_convert_to_hybrid_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name_search',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Lowercase version of first_name for efficient searching', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_search',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Lowercase version of last_name for efficient searching', max_length=255),
        ),
    ]
