# Generated by Django 5.2.3 on 2025-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_backfill_search_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='living_setting',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('assisted_living', 'Assisted Living'), ('nursing_home', 'Nursing Home'), ('hospital', 'Hospital/Acute Care'), ('rehab', 'Rehabilitation Facility'), ('other', 'Other')], help_text='Current living situation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_condition_id',
            field=models.CharField(blank=True, help_text='FHIR resource ID of primary diagnosis', max_length=100, null=True),
        ),
    ]
