# Generated by Django 5.2.3 on 2026-05-25 15:57

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_convert_jsonb_indexes_to_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 0009_convert_jsonb_indexes_to_gin already dropped the B-tree indexes and
    # created the GIN indexes via raw SQL, so the database side is done.
    # These operations only align Django's migration state with that reality —
    # running them against the database would fail with "already exists".
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='patient',
                    name='idx_medical_codes',
                ),
                migrations.RemoveIndex(
                    model_name='patient',
                    name='idx_encounter_dates',
                ),
                migrations.RemoveIndex(
                    model_name='patient',
                    name='idx_provider_refs',
                ),
                migrations.AddIndex(
                    model_name='patient',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['searchable_medical_codes'], name='idx_medical_codes_gin'),
                ),
                migrations.AddIndex(
                    model_name='patient',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['encounter_dates'], name='idx_encounter_dates_gin'),
                ),
                migrations.AddIndex(
                    model_name='patient',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['provider_references'], name='idx_provider_refs_gin'),
                ),
            ],
            database_operations=[],
        ),
    ]
