# Generated by Django 5.2.3 on 2025-10-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive name for this report configuration', max_length=100)),
                ('report_type', models.CharField(choices=[('patient_summary', 'Patient Summary Report'), ('provider_activity', 'Provider Activity Report'), ('document_audit', 'Document Processing Audit')], help_text='Type of report to generate', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters (filters, date ranges, options)')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this report contains')),
                ('is_favorite', models.BooleanField(default=False, help_text='Mark as favorite for quick access')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
                'db_table': 'report_configurations',
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Path to generated report file', max_length=255)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', help_text='Report output format', max_length=10)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate report (seconds)', null=True)),
                ('parameters_snapshot', models.JSONField(default=dict, help_text='Snapshot of parameters used (for audit)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of report generation', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(help_text='Configuration used to generate this report', on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reportconfiguration')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportconfiguration',
            index=models.Index(fields=['created_by', 'report_type'], name='report_conf_created_0ea679_idx'),
        ),
        migrations.AddIndex(
            model_name='reportconfiguration',
            index=models.Index(fields=['created_by', 'is_favorite'], name='report_conf_created_8ce67b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['created_by', 'status'], name='generated_r_created_2c621b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['configuration', '-created_at'], name='generated_r_configu_bc9bad_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['-created_at'], name='generated_r_created_c6db14_idx'),
        ),
    ]
