# Generated by Django 5.2.3 on 2025-10-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='configuration',
            field=models.ForeignKey(blank=True, help_text='Configuration used to generate this report (optional for ad-hoc reports)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reportconfiguration'),
        ),
    ]
